
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class forinmates extends javax.swing.JFrame {

    /**
     * Creates new form forinmates
     */
    public forinmates() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JFrame();
        tabpane = new javax.swing.JTabbedPane();
        Profile1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        detainee = new javax.swing.JComboBox<>();
        prison = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        sex = new javax.swing.JComboBox<>();
        alias = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        bdate = new datechooser.beans.DateChooserCombo();
        jLabel17 = new javax.swing.JLabel();
        bplace = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        add1 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        civil = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        rel = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        educ = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Profile2 = new javax.swing.JPanel();
        height = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        build = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        eye = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        hair = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        complex = new javax.swing.JTextField();
        nation = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        mark = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        Profile3 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        wh = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        child = new javax.swing.JTextField();
        occup = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        notif = new javax.swing.JTextField();
        acr = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Profile4 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        cc = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        dc = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        ccn = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        tc = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        st = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        ds = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        coun = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        addr = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        prev = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        prevtc = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        sent = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        dt = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        Image = new javax.swing.JPanel();
        j1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InmatesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ser = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        tabpane.setMaximumSize(new java.awt.Dimension(521, 559));
        tabpane.setMinimumSize(new java.awt.Dimension(521, 559));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Category");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Prison");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Detainee");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Others");

        detainee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Trial", "PD 1881", "Safekeeping" }));

        prison.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Insular", "Provincial", "City" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Name:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Age:");

        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ageKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel60.setText("Sex:");

        sex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel61.setText("Alias/Nickname:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Birth Date:");

        bdate.setCurrentView(new datechooser.view.appearance.AppearancesList("Dali",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    bdate.setCalendarPreferredSize(new java.awt.Dimension(284, 202));
    bdate.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));

    jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel17.setText("Birth Place:");

    jLabel62.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel62.setText("Address:");

    jLabel63.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel63.setText("Civil Status:");

    jLabel64.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel64.setText("Religion");

    jLabel65.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel65.setText("Highest Educ'l Attainment:");

    jButton1.setText("Save");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout Profile1Layout = new javax.swing.GroupLayout(Profile1);
    Profile1.setLayout(Profile1Layout);
    Profile1Layout.setHorizontalGroup(
        Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Profile1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1)
            .addGap(141, 141, 141))
        .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Profile1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Profile1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(77, 77, 77)
                        .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Profile1Layout.createSequentialGroup()
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(name)))
                    .addGroup(Profile1Layout.createSequentialGroup()
                        .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel63)
                            .addComponent(jLabel64))
                        .addGap(41, 41, 41)
                        .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(civil)
                            .addComponent(rel)))
                    .addGroup(Profile1Layout.createSequentialGroup()
                        .addComponent(jLabel65)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(educ))
                    .addGroup(Profile1Layout.createSequentialGroup()
                        .addComponent(jLabel61)
                        .addGap(18, 18, 18)
                        .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alias)))
                    .addGroup(Profile1Layout.createSequentialGroup()
                        .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel26)
                            .addComponent(jLabel62))
                        .addGap(45, 45, 45)
                        .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bplace)
                            .addComponent(add1)))
                    .addGroup(Profile1Layout.createSequentialGroup()
                        .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Profile1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Profile1Layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel12)
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel13)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel14))
                                    .addGroup(Profile1Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(prison, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(detainee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(13, 13, 13)))
    );
    Profile1Layout.setVerticalGroup(
        Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Profile1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1)
            .addGap(24, 24, 24))
        .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Profile1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detainee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel60)
                        .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Profile1Layout.createSequentialGroup()
                        .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26))
                    .addComponent(bdate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bplace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(civil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64))
                .addGap(18, 18, 18)
                .addGroup(Profile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(educ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    tabpane.addTab("Step 1", Profile1);

    jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel24.setText("Height (cm):");

    jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel25.setText("Weight(kg):");

    jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel27.setText("Build:");

    jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel34.setText("Eye:");

    jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel35.setText("Hair:");

    jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel46.setText("Complexion:");

    nation.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            nationActionPerformed(evt);
        }
    });

    jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel36.setText("Nationality:");

    jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel31.setText("Bertillion Marks (Scar, Mole, etc):");

    jButton4.setText("Next");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout Profile2Layout = new javax.swing.GroupLayout(Profile2);
    Profile2.setLayout(Profile2Layout);
    Profile2Layout.setHorizontalGroup(
        Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(Profile2Layout.createSequentialGroup()
            .addGroup(Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Profile2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Profile2Layout.createSequentialGroup()
                            .addGroup(Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel27)
                                .addComponent(jLabel34)
                                .addComponent(jLabel35)
                                .addComponent(jLabel46)
                                .addComponent(jLabel36))
                            .addGap(22, 22, 22)
                            .addGroup(Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hair)
                                .addComponent(eye)
                                .addComponent(complex)
                                .addComponent(nation)
                                .addComponent(build, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(Profile2Layout.createSequentialGroup()
                            .addComponent(jLabel31)
                            .addGap(18, 18, 18)
                            .addComponent(mark, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile2Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(weight))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile2Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(Profile2Layout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jButton4)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    Profile2Layout.setVerticalGroup(
        Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(Profile2Layout.createSequentialGroup()
            .addGap(38, 38, 38)
            .addGroup(Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel24)
                .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel25)
                .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(build, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel27))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel34)
                .addComponent(eye, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel35)
                .addComponent(hair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(complex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel46))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel36))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(Profile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel31)
                .addComponent(mark, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4)
            .addGap(52, 52, 52))
    );

    tabpane.addTab("Step 2", Profile2);

    jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel32.setText("Father's Name:");

    jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel39.setText("Mother's Name:");

    wh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            whActionPerformed(evt);
        }
    });

    jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel45.setText("Wife/Husband:");

    jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel40.setText("Children:");

    child.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            childActionPerformed(evt);
        }
    });

    occup.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            occupActionPerformed(evt);
        }
    });

    jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel55.setText("Occupation:");

    jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel33.setText("Person to notify in case of emergency:");

    jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel37.setText("ACR No.");

    jButton5.setText("Next");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout Profile3Layout = new javax.swing.GroupLayout(Profile3);
    Profile3.setLayout(Profile3Layout);
    Profile3Layout.setHorizontalGroup(
        Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Profile3Layout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(190, 190, 190))
        .addGroup(Profile3Layout.createSequentialGroup()
            .addGroup(Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(acr, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile3Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Profile3Layout.createSequentialGroup()
                            .addGroup(Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel39)
                                .addComponent(jLabel32)
                                .addGroup(Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel55)))
                            .addGap(35, 35, 35)
                            .addGroup(Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mname)
                                .addComponent(wh)
                                .addComponent(child)
                                .addComponent(occup, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fname, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))
                        .addGroup(Profile3Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Profile3Layout.createSequentialGroup()
                                    .addComponent(jLabel33)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(notif, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel37))))))
            .addGap(48, 48, 48))
    );
    Profile3Layout.setVerticalGroup(
        Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(Profile3Layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel32)
                .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel39)
                .addComponent(mname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel45)
                .addComponent(wh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel40)
                .addComponent(child, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(occup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel55))
            .addGap(18, 18, 18)
            .addGroup(Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel33)
                .addComponent(notif, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(Profile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel37)
                .addComponent(acr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28)
            .addComponent(jButton5)
            .addGap(22, 22, 22))
    );

    tabpane.addTab("Step 3", Profile3);

    jLabel48.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel48.setText("Crime Committed:");

    jLabel47.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel47.setText("Date Committed:");

    dc.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            dcActionPerformed(evt);
        }
    });

    jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel49.setText("Criminal Case No:");

    jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel50.setText("Trial Court:");

    tc.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tcActionPerformed(evt);
        }
    });

    jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel51.setText("Sentenced Term:");

    jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel52.setText("Date Sentenced:");

    ds.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            dsActionPerformed(evt);
        }
    });

    jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel53.setText("Counsel:");

    coun.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            counActionPerformed(evt);
        }
    });

    jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel54.setText("Address:");

    jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel56.setText("Previous Criminal records:");

    prev.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            prevActionPerformed(evt);
        }
    });

    jLabel57.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel57.setText("Trial Court:");

    prevtc.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            prevtcActionPerformed(evt);
        }
    });

    jLabel58.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel58.setText("Sentenced:");

    sent.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            sentActionPerformed(evt);
        }
    });

    jLabel59.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel59.setText("Date Released:");

    dt.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            dtActionPerformed(evt);
        }
    });

    jButton6.setText("Register");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout Profile4Layout = new javax.swing.GroupLayout(Profile4);
    Profile4.setLayout(Profile4Layout);
    Profile4Layout.setHorizontalGroup(
        Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(Profile4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(Profile4Layout.createSequentialGroup()
                    .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel58)
                        .addComponent(jLabel59))
                    .addGap(34, 34, 34)
                    .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sent)
                        .addComponent(dt)))
                .addComponent(jLabel51)
                .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile4Layout.createSequentialGroup()
                        .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50))
                        .addGap(18, 18, 18)
                        .addComponent(tc))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ccn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile4Layout.createSequentialGroup()
                                .addComponent(jLabel48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile4Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addGap(18, 18, 18)
                                .addComponent(dc)))))
                .addGroup(Profile4Layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Profile4Layout.createSequentialGroup()
                    .addComponent(jLabel52)
                    .addGap(20, 20, 20)
                    .addComponent(ds, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile4Layout.createSequentialGroup()
                        .addComponent(jLabel57)
                        .addGap(57, 57, 57)
                        .addComponent(prevtc))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile4Layout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prev))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile4Layout.createSequentialGroup()
                        .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel53)
                            .addComponent(jLabel54))
                        .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Profile4Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(coun, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Profile4Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGap(0, 180, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Profile4Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton6)
            .addGap(194, 194, 194))
    );
    Profile4Layout.setVerticalGroup(
        Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(Profile4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel48))
            .addGap(8, 8, 8)
            .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel47)
                .addComponent(dc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel49)
                .addComponent(ccn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel50)
                .addComponent(tc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel51))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ds, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel52))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Profile4Layout.createSequentialGroup()
                    .addComponent(jLabel53)
                    .addGap(23, 23, 23)
                    .addComponent(jLabel54))
                .addGroup(Profile4Layout.createSequentialGroup()
                    .addComponent(coun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel56)
                .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(prevtc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel57))
            .addGap(18, 18, 18)
            .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(sent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel58))
            .addGroup(Profile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Profile4Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabel59))
                .addGroup(Profile4Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
            .addComponent(jButton6))
    );

    tabpane.addTab("Step 4", Profile4);

    j1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    j1.setToolTipText("");
    j1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    j1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            j1MouseClicked(evt);
        }
    });

    jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton8.setText("Upload Photo");
    jButton8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton8ActionPerformed(evt);
        }
    });

    jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton9.setText("Save");
    jButton9.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton9ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout ImageLayout = new javax.swing.GroupLayout(Image);
    Image.setLayout(ImageLayout);
    ImageLayout.setHorizontalGroup(
        ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(ImageLayout.createSequentialGroup()
            .addGroup(ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ImageLayout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ImageLayout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jButton8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton9)))
            .addGap(96, 96, 96))
    );
    ImageLayout.setVerticalGroup(
        ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(ImageLayout.createSequentialGroup()
            .addGap(46, 46, 46)
            .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton8)
                .addComponent(jButton9))
            .addGap(62, 62, 62))
    );

    tabpane.addTab("Step5", Image);

    javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add.getContentPane());
    add.getContentPane().setLayout(addLayout);
    addLayout.setHorizontalGroup(
        addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(addLayout.createSequentialGroup()
            .addComponent(tabpane, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    addLayout.setVerticalGroup(
        addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(addLayout.createSequentialGroup()
            .addComponent(tabpane, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 20, Short.MAX_VALUE))
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    InmatesTable.setBackground(new java.awt.Color(204, 204, 204));
    InmatesTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "id", "Name", "Age", "Address", "Crime Committed", "Date Committed"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }
    });
    InmatesTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    InmatesTable.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            InmatesTableKeyPressed(evt);
        }
    });
    jScrollPane1.setViewportView(InmatesTable);

    jLabel1.setText("Name:");

    ser.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            serActionPerformed(evt);
        }
    });
    ser.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            serKeyPressed(evt);
        }
    });

    jButton10.setText("SEARCH");
    jButton10.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton10ActionPerformed(evt);
        }
    });

    jButton12.setText("Edit");
    jButton12.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton12ActionPerformed(evt);
        }
    });

    jButton11.setText("Print");

    jButton2.setText("Add");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel1)
                    .addGap(27, 27, 27)
                    .addComponent(ser, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton10))
                .addGroup(layout.createSequentialGroup()
                    .addGap(173, 173, 173)
                    .addComponent(jButton2)
                    .addGap(58, 58, 58)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(44, 44, 44)
                    .addComponent(jButton11)))
            .addContainerGap(240, Short.MAX_VALUE))
        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(ser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton10))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(183, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton11)
                        .addComponent(jButton12)
                        .addComponent(jButton2))
                    .addGap(130, 130, 130))))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InmatesTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InmatesTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_InmatesTableKeyPressed

    private void serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serActionPerformed

    private void serKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serKeyPressed
        String s = ser.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/system?", "root", "");
            Statement smt = con.createStatement();
            String sql = "SELECT * FROM profiles WHERE";

            if (s != (null)) {
                sql = sql + " (Name LIKE '%" + s + "%' )";
            }

            ResultSet rs = smt.executeQuery(sql);
            DefaultTableModel InmatesModel = new Inmate().inmate;
            int row = 0;
            while (rs.next()) {
               InmatesModel.addRow(new Object[]{});
                InmatesModel.setValueAt(rs.getString("Prisoner_ID"), row, 0);
                InmatesModel.setValueAt(rs.getString("Name"), row, 1);
                InmatesModel.setValueAt(rs.getString("Age"), row, 2);
                InmatesModel.setValueAt(rs.getString("Address"), row, 3);
                InmatesModel.setValueAt(rs.getString("CrimeCom"), row, 4);
                InmatesModel.setValueAt(rs.getString("DateCom"), row, 5);

                row++;
            }

            InmatesTable.setModel(InmatesModel);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_serKeyPressed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String s = ser.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/system?", "root", "");
            Statement smt = con.createStatement();
            String sql = "SELECT * FROM profiles WHERE";

            if (ser != (null)) {
                sql = sql + " (Name LIKE '%" + ser + "%' )";
            }

            ResultSet rs = smt.executeQuery(sql);
            DefaultTableModel InmatesModel = new Inmate().inmate;
            int row = 0;
            while (rs.next()) {
                InmatesModel.addRow(new Object[]{});
                InmatesModel.setValueAt(rs.getString("Prisoner_ID"), row, 0);
                InmatesModel.setValueAt(rs.getString("Name"), row, 1);
                InmatesModel.setValueAt(rs.getString("Age"), row, 2);
                InmatesModel.setValueAt(rs.getString("Address"), row, 3);
                InmatesModel.setValueAt(rs.getString("CrimeCom"), row, 4);
                InmatesModel.setValueAt(rs.getString("DateCom"), row, 5);

                row++;
            }

            InmatesTable.setModel(InmatesModel);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int selr = InmatesTable.getSelectedRow();
        if (selr != -1) {
            String id = (String) InmatesTable.getValueAt(selr, 0);

            
            add.setVisible(true);
            add.setAlwaysOnTop(true);
            //System.out.println(id);
            // jLabel1.setText("Edit Borrower");
            //this.reset_textfield();
            //jButton5.setVisible(false);
            // jButton6.setVisible(true);
          //  splitter.setRightComponent(Profile1);
            //form.setAlwaysOnTop(true);
            //form.setVisible(true);
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/system?", "root", "");

                Statement stmt = con.createStatement();

                ResultSet rs = stmt.executeQuery("select * from profiles where Prisoner_ID =" + id + ";");

                if (rs.next()) {
                    prison.setSelectedItem(rs.getString("prisoner"));
                    detainee.setSelectedItem(rs.getString("detainee"));
                    name.setText(rs.getString("name"));
                    age.setText(rs.getString("age"));
                    sex.setSelectedItem(rs.getString("sex"));
                    alias.setText(rs.getString("alias"));
                    bdate.setText(rs.getString("bday"));
                    bplace.setText(rs.getString("bplace"));
                    add1.setText(rs.getString("address"));
                    civil.setText(rs.getString("status"));
                    rel.setText(rs.getString("religion"));
                    educ.setText(rs.getString("EducAttain"));
                    height.setText(rs.getString("height"));
                    weight.setText(rs.getString("weight"));
                    build.setText(rs.getString("build"));
                    eye.setText(rs.getString("eye"));
                    hair.setText(rs.getString("hair"));
                    complex.setText(rs.getString("complexion"));
                    nation.setText(rs.getString("nationality"));
                    mark.setText(rs.getString("marks"));
                    fname.setText(rs.getString("FathersName"));
                    mname.setText(rs.getString("MothersName"));
                    wh.setText(rs.getString("WifeOrHusband"));
                    child.setText(rs.getString("Children"));
                    occup.setText(rs.getString("Occupation"));
                    notif.setText(rs.getString("PersonNotify"));
                    acr.setText(rs.getString("ACRno"));
                    cc.setText(rs.getString("CrimeCom"));
                    dc.setText(rs.getString("DateCom"));
                    ccn.setText(rs.getString("CaseNo"));
                    tc.setText(rs.getString("TrialCrt"));
                    st.setText(rs.getString("Term"));
                    ds.setText(rs.getString("DateSen"));
                    coun.setText(rs.getString("Counsel"));
                    addr.setText(rs.getString("CAddress"));
                    prev.setText(rs.getString("PrevRec"));
                    prevtc.setText(rs.getString("PrevTri"));
                    sent.setText(rs.getString("Sentenced"));
                    dt.setText(rs.getString("DateRel"));

                }

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void ageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageKeyPressed

    private void ageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyReleased
        try {
            int bg = Integer.parseInt(age.getText());

        } catch (NumberFormatException z) {
            JOptionPane.showMessageDialog(complex, "Incorrect Data Type");
            age.setText("");

            return;

        }
    }//GEN-LAST:event_ageKeyReleased

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ageKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String c = (String) prison.getSelectedItem();
        String c1 = (String) detainee.getSelectedItem();
        String n = name.getText();
        String ag = age.getText();
        int bg = Integer.parseInt(ag);
        String s = (String) sex.getSelectedItem();
        String al = alias.getText();
        String bd = bdate.getText();
        String bp = bplace.getText();
        String adr = add1.getText();
        String civ = civil.getText();
        String re = rel.getText();
        String edu = educ.getText();
        String h = height.getText();
        String w = weight.getText();
        String b = build.getText();
        String e = eye.getText();
        String ha = hair.getText();
        String com = complex.getText();
        String na = nation.getText();
        String m = mark.getText();
        String fa = fname.getText();
        String mo = mname.getText();
        String wi = wh.getText();
        String ch = child.getText();
        String oc = occup.getText();
        String noti = notif.getText();
        String acrn = acr.getText();
        String cr = cc.getText();
        String d = dc.getText();
        String no = ccn.getText();
        String tr = tc.getText();
        String sen = st.getText();
        String da = ds.getText();
        String co = coun.getText();
        String ad = addr.getText();
        String pr = prev.getText();

        String prv = prevtc.getText();
        String sentc = sent.getText();
        String dr = dt.getText();
        String im = j1.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(new conn().sqlconnect);
            String sql = "Insert into profiles VALUES(null,?, ?, ?, ?, ?,?, ?, ?, ?, ?,?, ?, ?, ?, ?,?, ?, ?, ?, ?,?, ?, ?, ?, ?,?, ?, ?, ?, ?,?, ?, ?, ?, ?,?, ?, ?, ?, ?)";
            PreparedStatement pstmt = con.prepareStatement(sql);

            pstmt.setString(1, c);
            pstmt.setString(2, c1);
            pstmt.setString(3, n);
            pstmt.setInt(4, bg);
            pstmt.setString(5, s);
            pstmt.setString(6, al);
            pstmt.setString(7, bd);
            pstmt.setString(8, bp);
            pstmt.setString(9, adr);
            pstmt.setString(10, civ);
            pstmt.setString(11, re);
            pstmt.setString(12, edu);
            pstmt.setString(13, h);
            pstmt.setString(14, w);
            pstmt.setString(15, b);
            pstmt.setString(16, e);
            pstmt.setString(17, ha);
            pstmt.setString(18, com);

            pstmt.setString(19, na);
            pstmt.setString(20, m);
            pstmt.setString(21, fa);
            pstmt.setString(22, mo);
            pstmt.setString(23, wi);
            pstmt.setString(24, ch);
            pstmt.setString(25, oc);
            pstmt.setString(26, noti);
            pstmt.setString(27, acrn);
            pstmt.setString(28, cr);
            pstmt.setString(29, d);
            pstmt.setString(30, no);
            pstmt.setString(31, tr);
            pstmt.setString(32, sen);
            pstmt.setString(33, da);
            pstmt.setString(34, co);
            pstmt.setString(35, ad);
            pstmt.setString(36, pr);

            pstmt.setString(37, prv);
            pstmt.setString(38, sentc);
            pstmt.setString(39, dr);
            pstmt.setString(40, im);

            pstmt.executeUpdate();

            //splitter.setRightComponent(Profile2);
            JOptionPane.showMessageDialog(complex, "Save");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String n = name.getText();
        String h = height.getText();
        String w = weight.getText();
        String b = build.getText();
        String e = eye.getText();
        String ha = hair.getText();
        String com = complex.getText();
        String na = nation.getText();
        String m = mark.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/system?", "root", "");
            PreparedStatement pstmt = con.prepareStatement("update profiles set Height=?, Weight=?, Build= ?, Eye =?, Hair= ?, Complexion=?, Nationality= ?, Marks= ? where Name = '" + n + "'");

            pstmt.setString(1, h);
            pstmt.setString(2, w);
            pstmt.setString(3, b);
            pstmt.setString(4, e);
            pstmt.setString(5, ha);
            pstmt.setString(6, com);

            pstmt.setString(7, na);
            pstmt.setString(8, m);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(complex, "Save");

            //  splitter.setRightComponent(Profile3);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void whActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whActionPerformed

    private void childActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childActionPerformed

    private void occupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String n = name.getText();
        String fa = fname.getText();
        String mo = mname.getText();
        String wi = wh.getText();
        String ch = child.getText();
        String oc = occup.getText();
        String noti = notif.getText();
        String acrn = acr.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/system?", "root", "");
            PreparedStatement pstmt = con.prepareStatement("update profiles set FathersName= ?, MothersName=?, WifeOrHusband=?, Children=?, Occupation=?,PersonNotify=?, ACRno=? where Name= '" + n + "'");

            pstmt.setString(1, fa);
            pstmt.setString(2, mo);
            pstmt.setString(3, wi);
            pstmt.setString(4, ch);
            pstmt.setString(5, oc);
            pstmt.setString(6, noti);
            pstmt.setString(7, acrn);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(complex, "Save");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void dcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcActionPerformed

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcActionPerformed

    private void dsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsActionPerformed

    private void counActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_counActionPerformed

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prevActionPerformed

    private void prevtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prevtcActionPerformed

    private void sentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sentActionPerformed

    private void dtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String n = name.getText();
        String cr = cc.getText();
        String d = dc.getText();
        String no = ccn.getText();
        String tr = tc.getText();
        String sen = st.getText();
        String da = ds.getText();
        String co = coun.getText();
        String ad = addr.getText();
        String pr = prev.getText();
        String prv = prevtc.getText();
        String sentc = sent.getText();
        String dr = dt.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(new conn().sqlconnect);
            PreparedStatement pstmt = con.prepareStatement("update profiles set CrimeCom= ?, DateCom= ?, CaseNo= ?, TrialCrt=?, Term= ?, DateSen=?, Counsel=?, CAddress=?, PrevRec=?, PrevTri=?, Sentenced=?,DateRel=? where Name= '" + n + "'");
            pstmt.setString(1, cr);
            pstmt.setString(2, d);
            pstmt.setString(3, no);
            pstmt.setString(4, tr);
            pstmt.setString(5, sen);
            pstmt.setString(6, da);
            pstmt.setString(7, co);
            pstmt.setString(8, ad);
            pstmt.setString(9, pr);
            pstmt.setString(10, prv);
            pstmt.setString(11, sentc);
            pstmt.setString(12, dr);

            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(complex, "Save");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void j1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseClicked

    }//GEN-LAST:event_j1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        
        
        
        
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       add.setVisible(true);
       add.setAlwaysOnTop(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forinmates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forinmates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forinmates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forinmates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forinmates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Image;
    private javax.swing.JTable InmatesTable;
    private javax.swing.JPanel Profile1;
    private javax.swing.JPanel Profile2;
    private javax.swing.JPanel Profile3;
    private javax.swing.JPanel Profile4;
    private javax.swing.JTextField acr;
    private javax.swing.JFrame add;
    private javax.swing.JTextField add1;
    private javax.swing.JTextField addr;
    private javax.swing.JTextField age;
    private javax.swing.JTextField alias;
    private datechooser.beans.DateChooserCombo bdate;
    private javax.swing.JTextField bplace;
    private javax.swing.JTextField build;
    private javax.swing.JTextField cc;
    private javax.swing.JTextField ccn;
    private javax.swing.JTextField child;
    private javax.swing.JTextField civil;
    private javax.swing.JTextField complex;
    private javax.swing.JTextField coun;
    private javax.swing.JTextField dc;
    private javax.swing.JComboBox<String> detainee;
    private javax.swing.JTextField ds;
    private javax.swing.JTextField dt;
    private javax.swing.JTextField educ;
    private javax.swing.JTextField eye;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField hair;
    private javax.swing.JTextField height;
    private javax.swing.JLabel j1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mark;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nation;
    private javax.swing.JTextField notif;
    private javax.swing.JTextField occup;
    private javax.swing.JTextField prev;
    private javax.swing.JTextField prevtc;
    private javax.swing.JComboBox<String> prison;
    private javax.swing.JTextField rel;
    private javax.swing.JTextField sent;
    private javax.swing.JTextField ser;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JTextField st;
    private javax.swing.JTabbedPane tabpane;
    private javax.swing.JTextField tc;
    private javax.swing.JTextField weight;
    private javax.swing.JTextField wh;
    // End of variables declaration//GEN-END:variables
}
